import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
	name: string;
	description: string;
	documentation: string;
};

const Home: NextPage = () => {
	const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

	return (
		<>
			<Head>
				<title>Duit Mana?</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-radial from-[#320541] to-[#1B0536] h-screen">
				<div className="container mx-auto flex flex-col items-center justify-center h-full p-4">
					<div className="animate-pulse bg-radial from-[#fff2002c] to-[#ffffff00] w-full h-full flex justify-center items-center absolute">
						<Image src="/images/question-mark.png" alt="Duit Mana?" width={200} height={200} />
					</div>
					<div className="py-40" />
					<h1 className="text-4xl font-bold text-white text-center">Duit Mana?</h1>
					<h3 className="text-[#E6BBFF] text-center mt-1">Designed by akasmirhan4</h3>
				</div>
			</main>
		</>
	);
};

export default Home;
