import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { getAuthSession } from "server/common/get-server-session";
import { Session } from "next-auth";
import { Navbar } from "components";
import React, { useCallback, useState } from "react";
import { CustomButton } from "components/form";
import { FiChevronLeft, FiRefreshCw } from "react-icons/fi";
import Link from "next/link";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
	const session = await getAuthSession(ctx);

	if (!session?.user) {
		return {
			redirect: {
				destination: "/auth/login",
				statusCode: 302,
			},
		};
	}

	return {
		props: { ...session.user },
	};
};

type PageProps = {
	user: Session["user"];
};

const Home: NextPage<PageProps> = (props) => {
	return (
		<>
			<Head>
				<title>Settings | Duit Mana?</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/images/icon.png" />
			</Head>

			<main className="bg-radial from-primary to-secondary min-h-screen">
				<Navbar />
				<div className="animate-pulse bg-radial from-[#fff2002c] to-[#ffffff00] w-full h-screen absolute pointer-events-none" />
				<div className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
					<div className="flex-1 flex flex-col justify-center items-center w-full max-w-md">
						<h1 className="text-xl text-center text-white">In the making process. Hang on tight! 🤗</h1>
						<Link href="/" passHref>
							<CustomButton startIcon={<FiChevronLeft />} label="Go Back" className="mt-8"/>
						</Link>
					</div>
				</div>
			</main>
		</>
	);
};

export default Home;
